server:
  port: 8080

spring:
  jpa:
    database: mysql
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

    h2.console.enabled: true

  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/carparking?useSSL=false
     username: root
     password: root

